/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NodeStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * NodeResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class NodeResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("port")
  private Integer port = 62050;

  @SerializedName("api_port")
  private Integer apiPort = 62051;

  @SerializedName("usage_coefficient")
  private BigDecimal usageCoefficient = new BigDecimal(1);

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("xray_version")
  private String xrayVersion = null;

  @SerializedName("status")
  private NodeStatus status = null;

  @SerializedName("message")
  private String message = null;

  public NodeResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NodeResponse address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(required = true, description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public NodeResponse port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @Schema(description = "")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public NodeResponse apiPort(Integer apiPort) {
    this.apiPort = apiPort;
    return this;
  }

   /**
   * Get apiPort
   * @return apiPort
  **/
  @Schema(description = "")
  public Integer getApiPort() {
    return apiPort;
  }

  public void setApiPort(Integer apiPort) {
    this.apiPort = apiPort;
  }

  public NodeResponse usageCoefficient(BigDecimal usageCoefficient) {
    this.usageCoefficient = usageCoefficient;
    return this;
  }

   /**
   * Get usageCoefficient
   * @return usageCoefficient
  **/
  @Schema(description = "")
  public BigDecimal getUsageCoefficient() {
    return usageCoefficient;
  }

  public void setUsageCoefficient(BigDecimal usageCoefficient) {
    this.usageCoefficient = usageCoefficient;
  }

  public NodeResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public NodeResponse xrayVersion(String xrayVersion) {
    this.xrayVersion = xrayVersion;
    return this;
  }

   /**
   * Get xrayVersion
   * @return xrayVersion
  **/
  @Schema(description = "")
  public String getXrayVersion() {
    return xrayVersion;
  }

  public void setXrayVersion(String xrayVersion) {
    this.xrayVersion = xrayVersion;
  }

  public NodeResponse status(NodeStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public NodeStatus getStatus() {
    return status;
  }

  public void setStatus(NodeStatus status) {
    this.status = status;
  }

  public NodeResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeResponse nodeResponse = (NodeResponse) o;
    return Objects.equals(this.name, nodeResponse.name) &&
        Objects.equals(this.address, nodeResponse.address) &&
        Objects.equals(this.port, nodeResponse.port) &&
        Objects.equals(this.apiPort, nodeResponse.apiPort) &&
        Objects.equals(this.usageCoefficient, nodeResponse.usageCoefficient) &&
        Objects.equals(this.id, nodeResponse.id) &&
        Objects.equals(this.xrayVersion, nodeResponse.xrayVersion) &&
        Objects.equals(this.status, nodeResponse.status) &&
        Objects.equals(this.message, nodeResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, port, apiPort, usageCoefficient, id, xrayVersion, status, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    apiPort: ").append(toIndentedString(apiPort)).append("\n");
    sb.append("    usageCoefficient: ").append(toIndentedString(usageCoefficient)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    xrayVersion: ").append(toIndentedString(xrayVersion)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
