/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NodeSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class NodeSettings {
  @SerializedName("min_node_version")
  private String minNodeVersion = "v0.2.0";

  @SerializedName("certificate")
  private String certificate = null;

  public NodeSettings minNodeVersion(String minNodeVersion) {
    this.minNodeVersion = minNodeVersion;
    return this;
  }

   /**
   * Get minNodeVersion
   * @return minNodeVersion
  **/
  @Schema(description = "")
  public String getMinNodeVersion() {
    return minNodeVersion;
  }

  public void setMinNodeVersion(String minNodeVersion) {
    this.minNodeVersion = minNodeVersion;
  }

  public NodeSettings certificate(String certificate) {
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @Schema(required = true, description = "")
  public String getCertificate() {
    return certificate;
  }

  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeSettings nodeSettings = (NodeSettings) o;
    return Objects.equals(this.minNodeVersion, nodeSettings.minNodeVersion) &&
        Objects.equals(this.certificate, nodeSettings.certificate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minNodeVersion, certificate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeSettings {\n");
    
    sb.append("    minNodeVersion: ").append(toIndentedString(minNodeVersion)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
