/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(NodeStatus.Adapter.class)
public enum NodeStatus {
  @SerializedName("connected")
  CONNECTED("connected"),
  @SerializedName("connecting")
  CONNECTING("connecting"),
  @SerializedName("error")
  ERROR("error"),
  @SerializedName("disabled")
  DISABLED("disabled");

  private String value;

  NodeStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static NodeStatus fromValue(String input) {
    for (NodeStatus b : NodeStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<NodeStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final NodeStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public NodeStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return NodeStatus.fromValue((String)(value));
    }
  }
}
