/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NodeUsageResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class NodeUsageResponse {
  @SerializedName("node_id")
  private Integer nodeId = null;

  @SerializedName("node_name")
  private String nodeName = null;

  @SerializedName("uplink")
  private Integer uplink = null;

  @SerializedName("downlink")
  private Integer downlink = null;

  public NodeUsageResponse nodeId(Integer nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  @Schema(description = "")
  public Integer getNodeId() {
    return nodeId;
  }

  public void setNodeId(Integer nodeId) {
    this.nodeId = nodeId;
  }

  public NodeUsageResponse nodeName(String nodeName) {
    this.nodeName = nodeName;
    return this;
  }

   /**
   * Get nodeName
   * @return nodeName
  **/
  @Schema(required = true, description = "")
  public String getNodeName() {
    return nodeName;
  }

  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }

  public NodeUsageResponse uplink(Integer uplink) {
    this.uplink = uplink;
    return this;
  }

   /**
   * Get uplink
   * @return uplink
  **/
  @Schema(required = true, description = "")
  public Integer getUplink() {
    return uplink;
  }

  public void setUplink(Integer uplink) {
    this.uplink = uplink;
  }

  public NodeUsageResponse downlink(Integer downlink) {
    this.downlink = downlink;
    return this;
  }

   /**
   * Get downlink
   * @return downlink
  **/
  @Schema(required = true, description = "")
  public Integer getDownlink() {
    return downlink;
  }

  public void setDownlink(Integer downlink) {
    this.downlink = downlink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeUsageResponse nodeUsageResponse = (NodeUsageResponse) o;
    return Objects.equals(this.nodeId, nodeUsageResponse.nodeId) &&
        Objects.equals(this.nodeName, nodeUsageResponse.nodeName) &&
        Objects.equals(this.uplink, nodeUsageResponse.uplink) &&
        Objects.equals(this.downlink, nodeUsageResponse.downlink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeId, nodeName, uplink, downlink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeUsageResponse {\n");
    
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
    sb.append("    uplink: ").append(toIndentedString(uplink)).append("\n");
    sb.append("    downlink: ").append(toIndentedString(downlink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
