/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * NodeModify
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class NodeModify {
  @SerializedName("name")
  private String name = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("port")
  private Integer port = null;

  @SerializedName("api_port")
  private Integer apiPort = null;

  @SerializedName("usage_coefficient")
  private BigDecimal usageCoefficient = null;

  @SerializedName("status")
  private AllOfNodeModifyStatus status = null;

  public NodeModify name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NodeModify address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public NodeModify port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @Schema(description = "")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public NodeModify apiPort(Integer apiPort) {
    this.apiPort = apiPort;
    return this;
  }

   /**
   * Get apiPort
   * @return apiPort
  **/
  @Schema(description = "")
  public Integer getApiPort() {
    return apiPort;
  }

  public void setApiPort(Integer apiPort) {
    this.apiPort = apiPort;
  }

  public NodeModify usageCoefficient(BigDecimal usageCoefficient) {
    this.usageCoefficient = usageCoefficient;
    return this;
  }

   /**
   * Get usageCoefficient
   * @return usageCoefficient
  **/
  @Schema(description = "")
  public BigDecimal getUsageCoefficient() {
    return usageCoefficient;
  }

  public void setUsageCoefficient(BigDecimal usageCoefficient) {
    this.usageCoefficient = usageCoefficient;
  }

  public NodeModify status(AllOfNodeModifyStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public AllOfNodeModifyStatus getStatus() {
    return status;
  }

  public void setStatus(AllOfNodeModifyStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeModify nodeModify = (NodeModify) o;
    return Objects.equals(this.name, nodeModify.name) &&
        Objects.equals(this.address, nodeModify.address) &&
        Objects.equals(this.port, nodeModify.port) &&
        Objects.equals(this.apiPort, nodeModify.apiPort) &&
        Objects.equals(this.usageCoefficient, nodeModify.usageCoefficient) &&
        Objects.equals(this.status, nodeModify.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, address, port, apiPort, usageCoefficient, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeModify {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    apiPort: ").append(toIndentedString(apiPort)).append("\n");
    sb.append("    usageCoefficient: ").append(toIndentedString(usageCoefficient)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
