/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(ProxyHostALPN.Adapter.class)
public enum ProxyHostALPN {
  @SerializedName("")
  EMPTY(""),
  @SerializedName("h3")
  H3("h3"),
  @SerializedName("h2")
  H2("h2"),
  @SerializedName("http/1.1")
  HTTP_1_1("http/1.1"),
  @SerializedName("h3,h2,http/1.1")
  H3_H2_HTTP_1_1("h3,h2,http/1.1"),
  @SerializedName("h3,h2")
  H3_H2("h3,h2"),
  @SerializedName("h2,http/1.1")
  H2_HTTP_1_1("h2,http/1.1");

  private String value;

  ProxyHostALPN(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProxyHostALPN fromValue(String input) {
    for (ProxyHostALPN b : ProxyHostALPN.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ProxyHostALPN> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProxyHostALPN enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ProxyHostALPN read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ProxyHostALPN.fromValue((String)(value));
    }
  }
}
