/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProxyTypes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ProxyInbound
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class ProxyInbound {
  @SerializedName("tag")
  private String tag = null;

  @SerializedName("protocol")
  private ProxyTypes protocol = null;

  @SerializedName("network")
  private String network = null;

  @SerializedName("tls")
  private String tls = null;

  @SerializedName("port")
  private AnyOfProxyInboundPort port = null;

  public ProxyInbound tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @Schema(required = true, description = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ProxyInbound protocol(ProxyTypes protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @Schema(required = true, description = "")
  public ProxyTypes getProtocol() {
    return protocol;
  }

  public void setProtocol(ProxyTypes protocol) {
    this.protocol = protocol;
  }

  public ProxyInbound network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Schema(required = true, description = "")
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }

  public ProxyInbound tls(String tls) {
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @Schema(required = true, description = "")
  public String getTls() {
    return tls;
  }

  public void setTls(String tls) {
    this.tls = tls;
  }

  public ProxyInbound port(AnyOfProxyInboundPort port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @Schema(required = true, description = "")
  public AnyOfProxyInboundPort getPort() {
    return port;
  }

  public void setPort(AnyOfProxyInboundPort port) {
    this.port = port;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyInbound proxyInbound = (ProxyInbound) o;
    return Objects.equals(this.tag, proxyInbound.tag) &&
        Objects.equals(this.protocol, proxyInbound.protocol) &&
        Objects.equals(this.network, proxyInbound.network) &&
        Objects.equals(this.tls, proxyInbound.tls) &&
        Objects.equals(this.port, proxyInbound.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, protocol, network, tls, port);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyInbound {\n");
    
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
