/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(ProxyTypes.Adapter.class)
public enum ProxyTypes {
  @SerializedName("vmess")
  VMESS("vmess"),
  @SerializedName("vless")
  VLESS("vless"),
  @SerializedName("trojan")
  TROJAN("trojan"),
  @SerializedName("shadowsocks")
  SHADOWSOCKS("shadowsocks");

  private String value;

  ProxyTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProxyTypes fromValue(String input) {
    for (ProxyTypes b : ProxyTypes.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ProxyTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProxyTypes enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ProxyTypes read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ProxyTypes.fromValue((String)(value));
    }
  }
}
