/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(ProxyHostFingerprint.Adapter.class)
public enum ProxyHostFingerprint {
  @SerializedName("")
  EMPTY(""),
  @SerializedName("chrome")
  CHROME("chrome"),
  @SerializedName("firefox")
  FIREFOX("firefox"),
  @SerializedName("safari")
  SAFARI("safari"),
  @SerializedName("ios")
  IOS("ios"),
  @SerializedName("android")
  ANDROID("android"),
  @SerializedName("edge")
  EDGE("edge"),
  @SerializedName("360")
  _360("360"),
  @SerializedName("qq")
  QQ("qq"),
  @SerializedName("random")
  RANDOM("random"),
  @SerializedName("randomized")
  RANDOMIZED("randomized");

  private String value;

  ProxyHostFingerprint(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProxyHostFingerprint fromValue(String input) {
    for (ProxyHostFingerprint b : ProxyHostFingerprint.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ProxyHostFingerprint> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProxyHostFingerprint enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ProxyHostFingerprint read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ProxyHostFingerprint.fromValue((String)(value));
    }
  }
}
