/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(ProxyHostSecurity.Adapter.class)
public enum ProxyHostSecurity {
  @SerializedName("inbound_default")
  INBOUND_DEFAULT("inbound_default"),
  @SerializedName("none")
  NONE("none"),
  @SerializedName("tls")
  TLS("tls");

  private String value;

  ProxyHostSecurity(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProxyHostSecurity fromValue(String input) {
    for (ProxyHostSecurity b : ProxyHostSecurity.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ProxyHostSecurity> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProxyHostSecurity enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ProxyHostSecurity read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ProxyHostSecurity.fromValue((String)(value));
    }
  }
}
