/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * UserTemplateResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class UserTemplateResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("data_limit")
  private Integer dataLimit = null;

  @SerializedName("expire_duration")
  private Integer expireDuration = null;

  @SerializedName("username_prefix")
  private String usernamePrefix = null;

  @SerializedName("username_suffix")
  private String usernameSuffix = null;

  @SerializedName("inbounds")
  private Map<String, List<String>> inbounds = null;

  @SerializedName("id")
  private Integer id = null;

  public UserTemplateResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserTemplateResponse dataLimit(Integer dataLimit) {
    this.dataLimit = dataLimit;
    return this;
  }

   /**
   * data_limit can be 0 or greater
   * minimum: 0
   * @return dataLimit
  **/
  @Schema(description = "data_limit can be 0 or greater")
  public Integer getDataLimit() {
    return dataLimit;
  }

  public void setDataLimit(Integer dataLimit) {
    this.dataLimit = dataLimit;
  }

  public UserTemplateResponse expireDuration(Integer expireDuration) {
    this.expireDuration = expireDuration;
    return this;
  }

   /**
   * expire_duration can be 0 or greater in seconds
   * minimum: 0
   * @return expireDuration
  **/
  @Schema(description = "expire_duration can be 0 or greater in seconds")
  public Integer getExpireDuration() {
    return expireDuration;
  }

  public void setExpireDuration(Integer expireDuration) {
    this.expireDuration = expireDuration;
  }

  public UserTemplateResponse usernamePrefix(String usernamePrefix) {
    this.usernamePrefix = usernamePrefix;
    return this;
  }

   /**
   * Get usernamePrefix
   * @return usernamePrefix
  **/
  @Schema(description = "")
  public String getUsernamePrefix() {
    return usernamePrefix;
  }

  public void setUsernamePrefix(String usernamePrefix) {
    this.usernamePrefix = usernamePrefix;
  }

  public UserTemplateResponse usernameSuffix(String usernameSuffix) {
    this.usernameSuffix = usernameSuffix;
    return this;
  }

   /**
   * Get usernameSuffix
   * @return usernameSuffix
  **/
  @Schema(description = "")
  public String getUsernameSuffix() {
    return usernameSuffix;
  }

  public void setUsernameSuffix(String usernameSuffix) {
    this.usernameSuffix = usernameSuffix;
  }

  public UserTemplateResponse inbounds(Map<String, List<String>> inbounds) {
    this.inbounds = inbounds;
    return this;
  }

  public UserTemplateResponse putInboundsItem(String key, List<String> inboundsItem) {
    if (this.inbounds == null) {
      this.inbounds = new HashMap<String, List<String>>();
    }
    this.inbounds.put(key, inboundsItem);
    return this;
  }

   /**
   * Get inbounds
   * @return inbounds
  **/
  @Schema(description = "")
  public Map<String, List<String>> getInbounds() {
    return inbounds;
  }

  public void setInbounds(Map<String, List<String>> inbounds) {
    this.inbounds = inbounds;
  }

  public UserTemplateResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserTemplateResponse userTemplateResponse = (UserTemplateResponse) o;
    return Objects.equals(this.name, userTemplateResponse.name) &&
        Objects.equals(this.dataLimit, userTemplateResponse.dataLimit) &&
        Objects.equals(this.expireDuration, userTemplateResponse.expireDuration) &&
        Objects.equals(this.usernamePrefix, userTemplateResponse.usernamePrefix) &&
        Objects.equals(this.usernameSuffix, userTemplateResponse.usernameSuffix) &&
        Objects.equals(this.inbounds, userTemplateResponse.inbounds) &&
        Objects.equals(this.id, userTemplateResponse.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dataLimit, expireDuration, usernamePrefix, usernameSuffix, inbounds, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserTemplateResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dataLimit: ").append(toIndentedString(dataLimit)).append("\n");
    sb.append("    expireDuration: ").append(toIndentedString(expireDuration)).append("\n");
    sb.append("    usernamePrefix: ").append(toIndentedString(usernamePrefix)).append("\n");
    sb.append("    usernameSuffix: ").append(toIndentedString(usernameSuffix)).append("\n");
    sb.append("    inbounds: ").append(toIndentedString(inbounds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
