/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(UserDataLimitResetStrategy.Adapter.class)
public enum UserDataLimitResetStrategy {
  @SerializedName("no_reset")
  NO_RESET("no_reset"),
  @SerializedName("day")
  DAY("day"),
  @SerializedName("week")
  WEEK("week"),
  @SerializedName("month")
  MONTH("month"),
  @SerializedName("year")
  YEAR("year");

  private String value;

  UserDataLimitResetStrategy(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserDataLimitResetStrategy fromValue(String input) {
    for (UserDataLimitResetStrategy b : UserDataLimitResetStrategy.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<UserDataLimitResetStrategy> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserDataLimitResetStrategy enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public UserDataLimitResetStrategy read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return UserDataLimitResetStrategy.fromValue((String)(value));
    }
  }
}
