/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * An enumeration.
 */
@JsonAdapter(UserStatusModify.Adapter.class)
public enum UserStatusModify {
  @SerializedName("active")
  ACTIVE("active"),
  @SerializedName("disabled")
  DISABLED("disabled"),
  @SerializedName("on_hold")
  ON_HOLD("on_hold");

  private String value;

  UserStatusModify(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static UserStatusModify fromValue(String input) {
    for (UserStatusModify b : UserStatusModify.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<UserStatusModify> {
    @Override
    public void write(final JsonWriter jsonWriter, final UserStatusModify enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public UserStatusModify read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return UserStatusModify.fromValue((String)(value));
    }
  }
}
