/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UserUsageResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-26T06:54:11.907891916Z[GMT]")

public class UserUsageResponse {
  @SerializedName("node_id")
  private Integer nodeId = null;

  @SerializedName("node_name")
  private String nodeName = null;

  @SerializedName("used_traffic")
  private Integer usedTraffic = null;

  public UserUsageResponse nodeId(Integer nodeId) {
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Get nodeId
   * @return nodeId
  **/
  @Schema(description = "")
  public Integer getNodeId() {
    return nodeId;
  }

  public void setNodeId(Integer nodeId) {
    this.nodeId = nodeId;
  }

  public UserUsageResponse nodeName(String nodeName) {
    this.nodeName = nodeName;
    return this;
  }

   /**
   * Get nodeName
   * @return nodeName
  **/
  @Schema(required = true, description = "")
  public String getNodeName() {
    return nodeName;
  }

  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }

  public UserUsageResponse usedTraffic(Integer usedTraffic) {
    this.usedTraffic = usedTraffic;
    return this;
  }

   /**
   * Get usedTraffic
   * @return usedTraffic
  **/
  @Schema(required = true, description = "")
  public Integer getUsedTraffic() {
    return usedTraffic;
  }

  public void setUsedTraffic(Integer usedTraffic) {
    this.usedTraffic = usedTraffic;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUsageResponse userUsageResponse = (UserUsageResponse) o;
    return Objects.equals(this.nodeId, userUsageResponse.nodeId) &&
        Objects.equals(this.nodeName, userUsageResponse.nodeName) &&
        Objects.equals(this.usedTraffic, userUsageResponse.usedTraffic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeId, nodeName, usedTraffic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUsageResponse {\n");
    
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
    sb.append("    usedTraffic: ").append(toIndentedString(usedTraffic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
