/*
 * MarzbanAPI
 * Unified GUI Censorship Resistant Solution Powered by Xray
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CoreStats;
import io.swagger.client.model.HTTPValidationError;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CoreApi
 */
@Ignore
public class CoreApiTest {

    private final CoreApi api = new CoreApi();

    /**
     * Get Core Config
     *
     * Get the current core configuration.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCoreConfigTest() throws Exception {
        Object response = api.getCoreConfig();

        // TODO: test validations
    }
    /**
     * Get Core Stats
     *
     * Retrieve core statistics such as version and uptime.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCoreStatsTest() throws Exception {
        CoreStats response = api.getCoreStats();

        // TODO: test validations
    }
    /**
     * Modify Core Config
     *
     * Modify the core configuration and restart the core.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void modifyCoreConfigTest() throws Exception {
        Object body = null;
        Object response = api.modifyCoreConfig(body);

        // TODO: test validations
    }
    /**
     * Restart Core
     *
     * Restart the core and all connected nodes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void restartCoreTest() throws Exception {
        Object response = api.restartCore();

        // TODO: test validations
    }
}
